
.. _`Cookiescutter-drf-microservice`: https://github.com/alainivars/cookiecutter-drf-microservice
.. _`{{cookiecutter.github_repository_name}}`: https://github.com/{{cookiecutter.github_username}}/{{cookiecutter.github_repository_name}}
.. _`Issue Cookiescutter-drf-microservice`: https://github.com/alainivars/cookiecutter-drf-microservice/issues
.. _`Issue Drf-microservice`: https://github.com/alainivars/drf-microservice/issues
.. _`Issue {{cookiecutter.github_repository_name}}`: https://github.com/{{cookiecutter.github_username}}/{{cookiecutter.github_repository_name}}/issues
.. _`Readthedoc`: https://{{cookiecutter.github_repository_name}}.readthedocs.io/en/latest/
.. _`Github`: https://github.com/{{cookiecutter.github_username}}/{{cookiecutter.github_repository_name}}
.. _`Releases notes`: https://github.com/{{cookiecutter.github_username}}/{{cookiecutter.github_repository_name}}/blob/master/docs/releases_notes.rst
