
.. _`Cookiescutter-drf-microservice`: https://github.com/alainivars/cookiecutter-drf-microservice
.. _`Drf-microservice`: https://github.com/alainivars/drf-microservice
.. _`Issue Cookiescutter-drf-microservice`: https://github.com/alainivars/cookiecutter-drf-microservice/issues
.. _`Issue Drf-microservice`: https://github.com/alainivars/drf-microservice/issues
.. _`Readthedoc`: https://drf-microservice.readthedocs.io/en/latest/
.. _`Github`: https://github.com/alainivars/cookiecutter-drf-microservice
.. _`Releases notes`: https://github.com/alainivars/cookiecutter-drf-microservice/blob/master/docs/releases_notes.rst
